language: php

php:
  # - 5.3
  - 5.4
  - 5.5
  - 5.6

services:
  - memcached

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - cp config/database.travis.yml config/database.yml
  - mysql -e 'create database kagu;'
  # - mysql -e 'use kagu;'
  - mysql -e 'create table users (id INT NOT NULL AUTO_INCREMENT, username VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, primary key(id));' kagu
  - mysql -e 'insert into users (username, password, created_at, updated_at) VALUES ("drager", "password", now(), now());'

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --verbose --coverage-clover build/logs/clover.xml tests/

after_script:
  - vendor/bin/coveralls

matrix:
  fast_finish: true

notifications:
  email: false
  irc: "irc.freenode.net#kagu"